/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mimimao_eric_fixcomma_FixcommA */

#ifndef _Included_com_mimimao_eric_fixcomma_FixcommA
#define _Included_com_mimimao_eric_fixcomma_FixcommA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _CreateObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1CreateObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _DeleteObject
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1DeleteObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetItemBuf
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetItemBuf
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _Link
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1Link
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _CreateHead
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1CreateHead
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _Close
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1Close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _More
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1More
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _SetTimeOut
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1SetTimeOut
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetDouble
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetDouble
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetFloat
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetFloat
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetLong
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetLong
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetString
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _GetItemString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1GetItemString
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _SetItemDouble
 * Signature: (IID)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1SetItemDouble
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _SetItemInt
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1SetItemInt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _SetItemString
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1SetItemString
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_mimimao_eric_fixcomma_FixcommA
 * Method:    _SetItemBuf
 * Signature: (II[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mimimao_eric_fixcomma_FixcommA__1SetItemBuf
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
